#!/usr/bin/env bash
set -euo pipefail

REPO_URL="https://github.com/Uniswap/docs"
BRANCH="main"
REPO_DIR="source-repo"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# --- Clone (skip if already exists) ---
if [ ! -d "$REPO_DIR" ]; then
    git clone --depth 1 --branch "$BRANCH" "$REPO_URL" "$REPO_DIR"
fi

cd "$REPO_DIR"

# --- Node version ---
# Node 20 is installed and satisfies >=18 requirement
echo "[INFO] Node version: $(node --version)"
echo "[INFO] Yarn version: $(yarn --version)"

# --- Dependencies ---
yarn install --frozen-lockfile

# --- Apply fixes.json if present ---
FIXES_JSON="$SCRIPT_DIR/fixes.json"
if [ -f "$FIXES_JSON" ]; then
    echo "[INFO] Applying content fixes..."
    node -e "
    const fs = require('fs');
    const path = require('path');
    const fixes = JSON.parse(fs.readFileSync('$FIXES_JSON', 'utf8'));
    for (const [file, ops] of Object.entries(fixes.fixes || {})) {
        if (!fs.existsSync(file)) { console.log('  skip (not found):', file); continue; }
        let content = fs.readFileSync(file, 'utf8');
        for (const op of ops) {
            if (op.type === 'replace' && content.includes(op.find)) {
                content = content.split(op.find).join(op.replace || '');
                console.log('  fixed:', file, '-', op.comment || '');
            }
        }
        fs.writeFileSync(file, content);
    }
    for (const [file, cfg] of Object.entries(fixes.newFiles || {})) {
        const c = typeof cfg === 'string' ? cfg : cfg.content;
        fs.mkdirSync(path.dirname(file), {recursive: true});
        fs.writeFileSync(file, c);
        console.log('  created:', file);
    }
    "
fi

# --- Fix duplicate sidebar translation keys ---
# Docusaurus write-translations fails when multiple sidebar categories share
# the same label (and thus the same translation key). We add a unique `key`
# attribute to every _category_.json file so each gets a distinct key.
# We also create _category_.json files for directories that lack one but would
# auto-generate a duplicate label (interfaces, classes, enums).
echo "[INFO] Fixing duplicate sidebar translation keys..."
node -e "
const fs = require('fs');
const path = require('path');

// Derive a stable sidebar key from a relative path, e.g.
// 'docs/contracts/v2/concepts' -> 'contracts-v2-concepts'
function pathToKey(relPath) {
    return relPath
        .replace(/^docs[\\/]/, '')
        .replace(/[\\/]/g, '-')
        .replace(/[^a-zA-Z0-9-]/g, '-')
        .toLowerCase();
}

// 1. Add unique 'key' to every existing _category_.json
function walkAndKey(dir) {
    if (!fs.existsSync(dir)) return;
    for (const entry of fs.readdirSync(dir, {withFileTypes: true})) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) {
            walkAndKey(full);
        } else if (entry.name === '_category_.json') {
            try {
                const content = JSON.parse(fs.readFileSync(full, 'utf8'));
                const key = pathToKey(path.dirname(full));
                content.key = key;
                fs.writeFileSync(full, JSON.stringify(content, null, 2) + '\n');
                console.log('  keyed:', full, '->', key);
            } catch (e) {
                console.log('  ERROR processing', full, e.message);
            }
        }
    }
}

walkAndKey('docs');

// 2. Create _category_.json for dirs that lack one but produce duplicate labels
// These directories generate autogenerated labels from their directory name,
// and multiple such directories exist with the same name.
const dirsNeedingCategory = [
    // 'interfaces' (lowercase autogenerated) - 4 dirs without _category_.json
    'docs/sdk/v3/reference/interfaces',
    'docs/sdk/v4/reference/interfaces',
    'docs/contracts/v4/reference/core/interfaces',
    'docs/contracts/v4/reference/periphery/interfaces',
    // 'classes' - 3 dirs without _category_.json
    'docs/sdk/core/reference/classes',
    'docs/sdk/v3/reference/classes',
    'docs/sdk/v4/reference/classes',
    // 'enums' - 2 dirs without _category_.json
    'docs/sdk/core/reference/enums',
    'docs/sdk/v3/reference/enums',
];

for (const dir of dirsNeedingCategory) {
    const catFile = path.join(dir, '_category_.json');
    if (!fs.existsSync(dir) || fs.existsSync(catFile)) continue;
    const label = path.basename(dir);
    const key = pathToKey(dir);
    const content = {label, key};
    fs.writeFileSync(catFile, JSON.stringify(content, null, 2) + '\n');
    console.log('  created:', catFile, '->', key);
}
"

echo "[DONE] Repository is ready for docusaurus commands."
